# Generated by Django 5.1.7 on 2025-03-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passconnectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
