# Generated by Django 5.1.7 on 2025-03-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passconnectApp', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
