# Generated by Django 5.1.7 on 2025-03-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passconnectApp', '0003_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
